#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and displays specific messages for certain iterations using a case statement

# Initialize counter
counter=1

# Use while loop to display numbers from 1 to 20
while [ $counter -le 20 ]; do
    # Use case statement to display different messages for specific iterations
    case $counter in
        4)
            echo "$counter"
            echo "bad luck from China"
            ;;
        9)
            echo "$counter"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$counter"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac
    ((counter++))
done
